FROM node:carbon

# Create app directory
WORKDIR /usr/src/app

ENV GOOGLE_APPLICATION_CREDENTIALS ./deployment/google-key.json

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package.json ./

RUN npm install
# RUN npm run postinstall
# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . .

EXPOSE 7072
CMD [ "npm", "run", "start:Docker" ]
